import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from 'react-hot-toast';

const inter = Poppins({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900", "900"], subsets: ['devanagari'] });

export const metadata: Metadata = {
  title: "ChatAPP — Chat with your favourite blogs.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>{children}</body>
        <Toaster />
      </html>
    </Providers>
  );
}
