import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from 'react-hot-toast';
import { ClerkProvider } from "@clerk/nextjs";


const inter = Poppins({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900", "900"], subsets: ['devanagari'] });

export const metadata: Metadata = {
  title: "ChatAPP — Chat with your favourite blogs.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <Providers>
          <body className={inter.className}>{children}</body>
          <Toaster />
        </Providers>
      </ClerkProvider>
    </html>
  );
}
